### ISSUE TITLE
Rigel 1.17.3: PANIC: panicked at rigel\src\miner\algorithm\xelishash\mod.rs:151:14: called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by Mihaxxi** [rigelminer/rigel#196]
Hi!

When zilika round started, i've started miner and... have this one (cycling). No any errors if i start miner out of zilika round. Please fixe it.

[2024-05-27 10:55:38] PANIC: panicked at rigel\src\miner\algorithm\xelishash\mod.rs:151:14:
called `Option::unwrap()` on a `None` value
[2024-05-27 10:55:43] miner started: -a xelishash+zil -o [1]stratum+ssl://ru.vipor.net:5177 -u [1] -o [2]stratum+ssl://eu.zil.k1pool.com:1111 -u [2] --cclock 250 --lock-cclock [1]1410 --lock-mclock [1]5001 --mclock [1]0 --lock-cclock [2]930 --lock-mclock [2]X --mclock [2]700 -w NvidiaRig10 --kernel 2 --no-strict-ssl --dns-over-https --log-file logs/miner.log --fan-control t:[53;_][55;50-95] --temp-limit tc[53-75]
[2024-05-27 10:55:43] Rigel v1.17.3 - [Windows]
[2024-05-27 10:55:43] 
[2024-05-27 10:55:43] Driver: v536.40
[2024-05-27 10:55:43] 
[2024-05-27 10:55:43] + GPU #0: RTX 3070 8G
[2024-05-27 10:55:43] + GPU #1: RTX 3070 8G
[2024-05-27 10:55:43] + GPU #2: RTX 3070 8G
[2024-05-27 10:55:43] + GPU #3: RTX 3070 8G
[2024-05-27 10:55:43] + GPU #4: RTX 3070 8G
[2024-05-27 10:55:43] 
[2024-05-27 10:55:43] Pools for xelishash (dev fee 3.0%):
[2024-05-27 10:55:43] URL:    ru.vipor.net:5177
[2024-05-27 10:55:43] User:   
[2024-05-27 10:55:43] Worker: NvidiaRig10
[2024-05-27 10:55:43] 
[2024-05-27 10:55:43] Pools for zil (dev fee 0.0%):
[2024-05-27 10:55:43] URL:    eu.zil.k1pool.com:1111
[2024-05-27 10:55:43] User:   
[2024-05-27 10:55:43] Worker: NvidiaRig10
[2024-05-27 10:55:43] 
[2024-05-27 10:55:44] [eu.zil.k1pool.com:1111] connecting...
[2024-05-27 10:55:44] [ru.vipor.net:5177] connecting...
[2024-05-27 10:55:44] [ru.vipor.net:5177] connected
[2024-05-27 10:55:44] [ru.vipor.net:5177] difficulty: 3.00M (0.00)
[2024-05-27 10:55:45] [eu.zil.k1pool.com:1111] connected
[2024-05-27 10:55:45] Light cache built
[2024-05-27 10:55:45] GPU#2: core offset set to +250
[2024-05-27 10:55:45] [eu.zil.k1pool.com:1111] difficulty: 5.00G (1.16)
[2024-05-27 10:55:45] Zilliqa session started
[2024-05-27 10:55:45] GPU#0: core offset set to +250
[2024-05-27 10:55:45] GPU#1: core offset set to +250
[2024-05-27 10:55:45] GPU#0: memory offset set to +700
[2024-05-27 10:55:45] GPU#4: core offset set to +250
[2024-05-27 10:55:45] GPU#0: locked core set to 930
[2024-05-27 10:55:45] GPU#2: memory offset set to +700
[2024-05-27 10:55:45] GPU#3: core offset set to +250
[2024-05-27 10:55:45] GPU#4: memory offset set to +700
[2024-05-27 10:55:45] GPU#0: locked memory set to `unlocked`
[2024-05-27 10:55:45] GPU#0: fan control set to [ Tc: 53°C ]; initial 55%; min 50%; max 95%
[2024-05-27 10:55:45] GPU#1: memory offset set to +700
[2024-05-27 10:55:45] GPU#2: locked core set to 930
[2024-05-27 10:55:45] GPU#3: memory offset set to +700
[2024-05-27 10:55:45] GPU#4: locked core set to 930
[2024-05-27 10:55:45] GPU#1: locked core set to 930
[2024-05-27 10:55:45] GPU#3: locked core set to 930
[2024-05-27 10:55:45] GPU#4: locked memory set to `unlocked`
[2024-05-27 10:55:45] GPU#4: fan control set to [ Tc: 53°C ]; initial 55%; min 50%; max 95%
[2024-05-27 10:55:45] GPU#1: locked memory set to `unlocked`
[2024-05-27 10:55:45] GPU#1: fan control set to [ Tc: 53°C ]; initial 55%; min 50%; max 95%
[2024-05-27 10:55:45] GPU#2: locked memory set to `unlocked`
[2024-05-27 10:55:45] GPU#2: fan control set to [ Tc: 53°C ]; initial 55%; min 50%; max 95%
[2024-05-27 10:55:45] GPU#3: locked memory set to `unlocked`
[2024-05-27 10:55:45] GPU#3: fan control set to [ Tc: 53°C ]; initial 55%; min 50%; max 95%
[2024-05-27 10:55:45] GPU#4: memory offset set to +0
[2024-05-27 10:55:45] GPU#4: building DAG for epoch 1, 1.08 GB
[2024-05-27 10:55:45] GPU#1: memory offset set to +0
[2024-05-27 10:55:45] GPU#1: building DAG for epoch 1, 1.08 GB
[2024-05-27 10:55:45] GPU#0: memory offset set to +0
[2024-05-27 10:55:45] GPU#0: building DAG for epoch 1, 1.08 GB
[2024-05-27 10:55:45] GPU#2: memory offset set to +0
[2024-05-27 10:55:45] GPU#2: building DAG for epoch 1, 1.08 GB
[2024-05-27 10:55:45] GPU#3: memory offset set to +0
[2024-05-27 10:55:45] GPU#3: building DAG for epoch 1, 1.08 GB
[2024-05-27 10:55:49] GPU#1: DAG built in 3.1s
[2024-05-27 10:55:49] GPU#2: DAG built in 3.1s
[2024-05-27 10:55:49] GPU#3: DAG built in 3.1s
[2024-05-27 10:55:49] GPU#4: DAG built in 3.1s
[2024-05-27 10:55:49] GPU#0: DAG built in 3.1s
[2024-05-27 10:55:49] GPU#1: memory offset set to +700
[2024-05-27 10:55:49] GPU#3: memory offset set to +700
[2024-05-27 10:55:49] GPU#0: memory offset set to +700
[2024-05-27 10:55:49] GPU#2: memory offset set to +700
[2024-05-27 10:55:49] GPU#3: memory offset set to +0
[2024-05-27 10:55:49] GPU#3: locked core set to 1410
[2024-05-27 10:55:49] GPU#4: memory offset set to +700
[2024-05-27 10:55:49] GPU#1: memory offset set to +0
[2024-05-27 10:55:49] GPU#1: locked core set to 1410
[2024-05-27 10:55:49] GPU#3: locked memory set to 5001
[2024-05-27 10:55:49] GPU#1: locked memory set to 5001
[2024-05-27 10:55:49] GPU#2: memory offset set to +0
[2024-05-27 10:55:49] GPU#2: locked core set to 1410
[2024-05-27 10:55:49] GPU#0: memory offset set to +0
[2024-05-27 10:55:49] GPU#0: locked core set to 1410
[2024-05-27 10:55:49] GPU#4: memory offset set to +0
[2024-05-27 10:55:49] GPU#2: locked memory set to 5001
[2024-05-27 10:55:49] GPU#4: locked core set to 1410
[2024-05-27 10:55:49] GPU#4: locked memory set to 5001
[2024-05-27 10:55:49] GPU#0: locked memory set to 5001
[2024-05-27 10:55:49] PANIC: panicked at rigel\src\miner\algorithm\xelishash\mod.rs:151:14:
called `Option::unwrap()` on a `None` value
[2024-05-27 10:55:54] miner started: -a xelishash+zil -o [1]stratum+ssl://ru.vipor.net:5177 -u [1]xel: -o [2]stratum+ssl://eu.zil.k1pool.com:1111 -u [2] --cclock 250 --lock-cclock [1]1410 --lock-mclock [1]5001 --mclock [1]0 --lock-cclock [2]930 --lock-mclock [2]X --mclock [2]700 -w NvidiaRig10 --kernel 2 --no-strict-ssl --dns-over-https --log-file logs/miner.log --fan-control t:[53;_][55;50-95] --temp-limit tc[53-75]
[2024-05-27 10:55:54] Rigel v1.17.3 - [Windows]
[2024-05-27 10:55:54] 
[2024-05-27 10:55:55] Driver: v536.40
[2024-05-27 10:55:55] 
[2024-05-27 10:55:55] + GPU #0: RTX 3070 8G
[2024-05-27 10:55:55] + GPU #1: RTX 3070 8G
[2024-05-27 10:55:55] + GPU #2: RTX 3070 8G
[2024-05-27 10:55:55] + GPU #3: RTX 3070 8G
[2024-05-27 10:55:55] + GPU #4: RTX 3070 8G
[2024-05-27 10:55:55] 
[2024-05-27 10:55:55] Pools for xelishash (dev fee 3.0%):
[2024-05-27 10:55:55] URL:    ru.vipor.net:5177
[2024-05-27 10:55:55] User:   xel:
[2024-05-27 10:55:55] Worker: NvidiaRig10
[2024-05-27 10:55:55] 
[2024-05-27 10:55:55] Pools for zil (dev fee 0.0%):
[2024-05-27 10:55:55] URL:    eu.zil.k1pool.com:1111
[2024-05-27 10:55:55] User:   
[2024-05-27 10:55:55] Worker: NvidiaRig10
[2024-05-27 10:55:55] 
[2024-05-27 10:55:55] [eu.zil.k1pool.com:1111] connecting...
[2024-05-27 10:55:55] [ru.vipor.net:5177] connecting...
[2024-05-27 10:55:55] [ru.vipor.net:5177] connected
[2024-05-27 10:55:56] [ru.vipor.net:5177] difficulty: 3.00M (0.00)
[2024-05-27 10:55:56] [eu.zil.k1pool.com:1111] connected
[2024-05-27 10:55:56] Light cache built
[2024-05-27 10:55:56] [eu.zil.k1pool.com:1111] difficulty: 5.00G (1.16)
[2024-05-27 10:55:56] Zilliqa session started
[2024-05-27 10:55:56] GPU#3: core offset set to +250
[2024-05-27 10:55:56] GPU#1: core offset set to +250
[2024-05-27 10:55:56] GPU#4: core offset set to +250
[2024-05-27 10:55:56] GPU#0: core offset set to +250
[2024-05-27 10:55:56] GPU#4: memory offset set to +700
[2024-05-27 10:55:56] GPU#4: locked core set to 930
[2024-05-27 10:55:56] GPU#0: memory offset set to +700
[2024-05-27 10:55:56] GPU#2: core offset set to +250
[2024-05-27 10:55:56] GPU#3: memory offset set to +700
[2024-05-27 10:55:56] GPU#2: memory offset set to +700
[2024-05-27 10:55:56] GPU#0: locked core set to 930
[2024-05-27 10:55:56] GPU#1: memory offset set to +700
[2024-05-27 10:55:56] GPU#4: locked memory set to `unlocked`
[2024-05-27 10:55:56] GPU#4: fan control set to [ Tc: 53°C ]; initial 55%; min 50%; max 95%
[2024-05-27 10:55:56] GPU#3: locked core set to 930
[2024-05-27 10:55:56] GPU#4: memory offset set to +0
[2024-05-27 10:55:56] GPU#4: building DAG for epoch 1, 1.08 GB
[2024-05-27 10:55:56] GPU#0: locked memory set to `unlocked`
[2024-05-27 10:55:56] GPU#0: fan control set to [ Tc: 53°C ]; initial 55%; min 50%; max 95%
[2024-05-27 10:55:56] GPU#2: locked core set to 930
[2024-05-27 10:55:56] GPU#1: locked core set to 930
[2024-05-27 10:55:56] GPU#3: locked memory set to `unlocked`
[2024-05-27 10:55:56] GPU#3: fan control set to [ Tc: 53°C ]; initial 55%; min 50%; max 95%
[2024-05-27 10:55:56] GPU#2: locked memory set to `unlocked`
[2024-05-27 10:55:56] GPU#2: fan control set to [ Tc: 53°C ]; initial 55%; min 50%; max 95%
[2024-05-27 10:55:56] GPU#0: memory offset set to +0
[2024-05-27 10:55:56] GPU#0: building DAG for epoch 1, 1.08 GB
[2024-05-27 10:55:56] GPU#1: locked memory set to `unlocked`
[2024-05-27 10:55:56] GPU#1: fan control set to [ Tc: 53°C ]; initial 55%; min 50%; max 95%
[2024-05-27 10:55:56] GPU#3: memory offset set to +0
[2024-05-27 10:55:56] GPU#3: building DAG for epoch 1, 1.08 GB
[2024-05-27 10:55:56] GPU#2: memory offset set to +0
[2024-05-27 10:55:56] GPU#2: building DAG for epoch 1, 1.08 GB
[2024-05-27 10:55:57] GPU#1: memory offset set to +0
[2024-05-27 10:55:57] GPU#1: building DAG for epoch 1, 1.08 GB
[2024-05-27 10:56:00] GPU#1: DAG built in 3.1s
[2024-05-27 10:56:00] GPU#2: DAG built in 3.1s
[2024-05-27 10:56:00] GPU#3: DAG built in 3.0s
[2024-05-27 10:56:00] GPU#4: DAG built in 3.1s
[2024-05-27 10:56:00] GPU#0: DAG built in 3.1s
[2024-05-27 10:56:00] GPU#1: memory offset set to +700
[2024-05-27 10:56:00] GPU#4: memory offset set to +700
[2024-05-27 10:56:00] GPU#0: memory offset set to +700
[2024-05-27 10:56:00] GPU#2: memory offset set to +700
[2024-05-27 10:56:00] GPU#3: memory offset set to +700
[2024-05-27 10:56:00] GPU#0: memory offset set to +0
[2024-05-27 10:56:00] GPU#0: locked core set to 1410
[2024-05-27 10:56:00] GPU#0: locked memory set to 5001
[2024-05-27 10:56:00] GPU#3: memory offset set to +0
[2024-05-27 10:56:00] GPU#1: memory offset set to +0
[2024-05-27 10:56:00] GPU#3: locked core set to 1410
[2024-05-27 10:56:00] GPU#1: locked core set to 1410
[2024-05-27 10:56:00] GPU#4: memory offset set to +0
[2024-05-27 10:56:00] GPU#2: memory offset set to +0
[2024-05-27 10:56:00] GPU#4: locked core set to 1410
[2024-05-27 10:56:00] GPU#2: locked core set to 1410
[2024-05-27 10:56:00] GPU#3: locked memory set to 5001
[2024-05-27 10:56:00] GPU#1: locked memory set to 5001
[2024-05-27 10:56:00] GPU#4: locked memory set to 5001
[2024-05-27 10:56:00] GPU#2: locked memory set to 5001
[2024-05-27 10:56:00] PANIC: panicked at rigel\src\miner\algorithm\xelishash\mod.rs:151:14:
called `Option::unwrap()` on a `None` value

**Comment by rigelminer** [comment]
Thanks for reporting, I'll fix it in the next version

**Comment by rigelminer** [comment]
Yeah, it's a known issue and it occurs irrespective of how many GPUs there are in the rig. It only happens on XEL+ZIL when you start the miner during a ZIL round. If you start outside of it, the issue will never happen. I'll release the fix in 1.17.4

**Comment by 7runks** [comment]
> Yeah, it's a known issue and it occurs irrespective of how many GPUs there are in the rig. It only happens on XEL+ZIL when you start the miner during a ZIL round. If you start outside of it, the issue will never happen. I'll release the fix in 1.17.4

Thank you.

**Comment by rigelminer** [comment]
Should be fixed in 1.17.4
